language: python

branches:
  only:
    - master
python:
  - "3.5"
cache: pip
sudo: required
addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
     
install:
  - make development
  # requirement for coveralls.io
  - pip install coveralls

before_script:
  # start virtual X server (needed for the functional tests)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  
script:
  # run all tests
  make coverage +c

# send coverage report to coveralls.io
after_success:
  - pushd src
  - coveralls
  - popd

deploy:
  # deploy / build the docker image
  provider: script
  script: curl --data build=true -X POST $DOCKERHUB_WEBHOOK_URL
