language: python

branches:
  only:
    - master
python:
  - "3.5"
cache: pip
sudo: required 
addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
     
install:
  - make development
  # requirement for coveralls.io
  - pip install coveralls
#   # Ansible is required for deployment
#   - pip install ansible

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  
script:
  - make coverage_func

# send coverage report to coveralls.io
after_success:
  - pushd src
  - coveralls
  - popd

# deploy:
#   # deploy to the staging environment
#   - provider: script
#     script: bash tools/scripts/deploy_staging.sh
#   # deploy to production
#   - provider: script
#     script: bash tools/scripts/deploy_production.sh
