language: python

branches:
  only:
    - master
python:
  - "3.5"
cache: pip
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - libexempi3
install:
  - make development
  # requirement for coveralls.io
  - pip install coveralls

before_script:
  # add the chromedriver binary to the PATH
  - export PATH=$PATH:`chromedriver-path`
  
script:
  # run all tests
  make coverage +c

# send coverage report to coveralls.io
after_success:
  - pushd src
  - coveralls
  - popd

deploy:
  # deploy / build the docker image
  provider: script
  script: curl --request POST --header Content-Type:application/json --data {"build":true} --url $DOCKERHUB_WEBHOOK_URL
